seed: 42
#finetune
pubmed_datapath: "gayanin/pubmed-mixed-noise"
subset: "prob-0.2"
pretrained_modelname: "google/flan-t5-base"
block_size: 128
batch_size: 4
colname: "trans"
checkpoint_dir: "./ec-model"
overwrite_output_dir: True
evaluation_strategy: "steps"
save_strategy: "steps"
num_train_epochs: 3
per_device_train_batch_size: 2
per_device_eval_batch_size: 2
eval_steps: 500
save_steps: 500
warmup_steps: 10
logging_steps: 10
logging_dir: "./logs"
push_to_hub: True
fine_tuned_model: "gayanin/pubmed-mixed-noise-v5-0.2"
fp16: True
load_best_model_at_end: True
save_total_limit: 5
##generate
generate_dir: "model_outputs/" 
gcd_datapath: "gayanin/gcd-native"
babylon_datapath: "gayanin/babylon-native"
kaggle_datapath: "gayanin/kaggle-native"
max_length: 128
num_return_sequences: 1
no_repeat_ngram_size: 2
##testing
eval_dir: "results/"
baseline: True