seed: 42
#finetune
pubmed_datapath: "gayanin/gcd-native-v8-vocab-noised"
subset: "prob-0.1"
pretrained_modelname: "bart-with-vocab-noise-data"
block_size: 128
batch_size: 32
colname: "trans"
checkpoint_dir: "./ec-model1"
overwrite_output_dir: True
evaluation_strategy: "steps"
save_strategy: "steps"
num_train_epochs: 3
per_device_train_batch_size: 16
per_device_eval_batch_size: 16
eval_steps: 500
save_steps: 500
warmup_steps: 10
logging_steps: 10
logging_dir: "./logs"
push_to_hub: True
fine_tuned_model: "gayanin/bart-with-vocab-noise-data"
# fine_tuned_model: "facebook/bart-base" #for baseline without fine-tuning
fp16: True
load_best_model_at_end: True
save_total_limit: 5
##generate
generate_dir: "model_outputs/bart-base/v11/" 
gcd_datapath: "gayanin/gcd-native-v8-vocab-noised"
babylon_datapath: "gayanin/babylon-native-v8-vocab-noised"
kaggle_datapath: "gayanin/kaggle-native-v8-vocab-noised"
max_length: 128
num_return_sequences: 1
no_repeat_ngram_size: 2
##testing
eval_dir: "results/bart-base/v11/"
baseline: True